slam_toolbox:
  ros__parameters:
    # 1. Basic Framework
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    # 2. Map Settings
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0

    # 3. Memory management (Good for Pi)
    max_poly_nodes: 0
    stack_size_to_use: 40000000